#!/bin/sh

FIROOT="/Volumes/src2/fink/selfupdate"
LOCKFILE="/var/run/finkrsyncup.lock"
SSHUSER="finkcvs"
CVSARGS=""

usage() {
	cat > "/dev/stderr" << EOF
usage: ${0} [ -l <lockfile> ] [ -o <outputdir> ] [-u <sshuser> ] [ -q ]
Defaults:
	outputdir: ${FIROOT}
	lockfile: ${LOCKFILE}
	sshuser: ${SSHUSER}
EOF
	exit 1
}

while getopts ":l:o:u:q" OPTION; do
	case "${OPTION}" in
		l)
			LOCKFILE=${OPTARG}
		;;
		o)
			FIROOT=${OPTARG}
		;;
		u)
			SSHUSER=${OPTARG}
		;;
		q)
			CVSARGS=" -q "
		;;
		?)
			usage
		;;
	esac
done

export CVS_RSH=ssh

lockfile -r 0 "${LOCKFILE}" || exit 0

cd "${FIROOT}"

if /usr/bin/cvs -d :ext:${SSHUSER}@fink.cvs.sourceforge.net:/cvsroot/fink ${CVSARGS} -z3 co -d finkinfo.tmp dists; then
	if rsync -a --delete --exclude=.cvsignore --exclude=CVS "${FIROOT}/finkinfo.tmp/" "${FIROOT}/finkinfo/"; then
		echo "$(date -u +%s)" > "${FIROOT}/finkinfo/TIMESTAMP";
	fi;
fi

rm -f "${LOCKFILE}"
