#!/bin/sh

FIROOT="/Volumes/src2/fink/selfupdate"
LOCKFILE="/var/run/finkrsyncup.lock"
SSHUSER="finkcvs"
CVSARGS=""

usage() {
	cat > "/dev/stderr" << EOF
usage: $0 [-l lockfile] [-o outputdir]
EOF
	exit
}

while getopts ":l:o:u:hq" OPTION; do
	case "${OPTION}" in
		l)
			LOCKFILE=${OPTARG}
			;;
		o)
			FIROOT=${OPTARG}
			;;
		u)
			SSHUSER=${OPTARG}
			;;
		q)
			CVSARGS=" -q "
			;;
		h | ?)
			usage
			;;
	esac
done

export CVS_RSH=ssh

lockfile -r 0 "${LOCKFILE}" || exit 0

cd "${FIROOT}"

if /usr/bin/cvs -d :ext:${SSHUSER}@fink.cvs.sourceforge.net:/cvsroot/fink ${CVSARGS} -z3 co -d finkinfo.tmp dists; then
	if rsync -a --delete --exclude=.cvsignore --exclude=CVS "${FIROOT}/finkinfo.tmp/" "${FIROOT}/finkinfo/"; then
		echo "$(date -u +%s)" > "${FIROOT}/finkinfo/TIMESTAMP";
	fi;
fi

rm -f "${LOCKFILE}"
