#!/bin/sh

FIROOT="/Volumes/src2/fink/selfupdate"
LOCKFILE="/var/run/finkrsyncup.lock"

usage() {
	cat > "/dev/stderr" << EOF
usage: $0 [-l lockfile] [-o outputdir]
EOF
	exit
}

while getopts ":l:o:h" OPTION; do
	case "${OPTION}" in
		l)
			LOCKFILE=${OPTARG}
			;;
		o)
			FIROOT=${OPTARG}
			;;
		h | ?)
			usage
			;;
	esac
done

export CVS_RSH=ssh

lockfile -r 0 "${LOCKFILE}" || exit 0

cd "${FIROOT}"

/usr/bin/cvs -d :ext:finkcvs@fink.cvs.sourceforge.net:/cvsroot/fink -z3 co -d finkinfo.tmp dists

rsync -a --delete --exclude=.cvsignore --exclude=CVS "${FIROOT}/finkinfo.tmp/" "${FIROOT}/finkinfo/"

echo "$(date -u +%s)" > "${FIROOT}/finkinfo/TIMESTAMP"

rm -f "${LOCKFILE}"
