#!/usr/bin/perl
#Make the /sw symlink - this should work fine, we checked for /sw in InstallationCheck
if(! -e "/sw")
{
 # Only make the link if we didn't install on the root volume
 `/bin/ln -s \"$ARGV[1]/sw\" /sw`;
}
