#!/usr/bin/perl
#Make the /sw symlink - this should work fine, we checked for /sw in InstallationCheck
if(! -e "/sw")
{
 # Only make the link if we didn't install on the root volume
 `/bin/ln -s \"$ARGV[1]/sw\" /sw`;
}
system "/usr/bin/yes '' | /sw/lib/fink/postinstall.pl";
system "/sw/bin/fink -y index";
system "/sw/bin/pathsetup.sh; osascript -e 'tell application \"Installer\"' -e 'activate' -e 'end tell'";
system "/sw/var/lib/fink/prebound/update-package-prebinding.pl -f";
