#!/usr/bin/perl
use File::Find;

my $result = 0, $basedir = "/sw";
my $PACKAGE_PATH = $ENV{PACKAGE_PATH};
my $TARGET_VOLUME = $ARGV[0];
my $targetdir = "$TARGET_VOLUME$basedir";

DO_CHECKS:
{
	# The "18" specifies the index of the localized error string in
	# {English,Spanish,etc}.lproj/VolumeCheck.strings
	if ((-e "$targetdir") || (-l "$targetdir"))
	{
	  print "Fink Installer: $targetdir exists!\n";
	  $result = ((1 << 5) | 18);
  	  last;
	}

	if (! -w "${TARGET_VOLUME}")
	{
	    print "Fink Installer: User $ENV{USER} cannot write to ${TARGET_VOLUME} to perform symlink test! Try performing the \"Repair Permissions\" function in Disk Utility.\n";
	    $result = ((1 << 5) | 22);
	    last;
	}

	if (symlink("$targetdir.tmp", "$targetdir"))
	{
	    unlink("$targetdir");
	} else {
	    print "Fink Installer: ${TARGET_VOLUME} does not support symlinks ($!)!\n";
	    $result = ((1 << 5) | 21);
	    last;
	}
}

exit $result;


