#!/usr/bin/perl

$| = 1;
use v5.6.0;  # perl 5.6.0 or newer required
use strict;

my $base = "/Users/chrisp/fink/web/bindist";
chdir $base;

my $dest = "dists/fink-0.2.5/main";

### now load the useful modules

use Fink::Services qw(&read_config &filename &execute);
use Fink::Config;
use Fink::Package;
use Fink::PkgVersion;

### read config

my $config = &read_config("/sw/etc/fink.conf");

### read package info

Fink::Package->require_packages();

### loop over packages

my ($pkgspec, $pkgname, $po, $fn, $todir, $tofn, $i);

foreach $pkgspec (@ARGV) {
  $po = Fink::PkgVersion->match_package($pkgspec);
  if (not defined($po)) {
    print "ERROR: can't resolve \"$pkgspec\"\n";
    next;
  }
  $pkgname = $po->get_fullname();

  $fn = $po->find_debfile();
  if (not defined($fn)) {
    print "ERROR: no binary package for $pkgname\n";
    next;
  }
  $todir = $dest."/binary-darwin-powerpc/".$po->get_section();
  $tofn = $todir."/".&filename($fn);
  if (not -d $todir) {
    &execute("mkdir -p $todir");
  }
  &execute("cp $fn $tofn");

  for ($i = 1; $i < 10; $i++) {
    $fn = $po->get_tarball($i);
    last if $fn eq "-";

    if (not -f "source/$fn") {
      $fn = $po->find_tarball($i);
      if (not defined($fn)) {
	print "WARNING: can't find source package \"".$po->get_tarball($i)."\" for $pkgname\n";
	next;
      }
      $tofn = "source/".&filename($fn);
      &execute("cp $fn $tofn");
    }

    $todir = $dest."/source/".$po->get_section();
    $tofn = $todir."/".&filename($fn);
    if (not -f $tofn) {
      if (not -d $todir) {
	&execute("mkdir -p $todir");
      }
      &execute("ln -s ../../../../../source/".&filename($fn)." $tofn");
    }
  }
}

&execute("./genindex.pl");

exit 0;
