#!/bin/sh

tree=$1
if [ -z "$tree" ]; then
  tree="fink-`cat $BDDATA/current`"
  echo "Defaulting to tree $tree"
fi

$BDDATA/bdlist $tree | cut -f1 -d_ > /tmp/fink_bindist
cat $BDDATA/excludes >> /tmp/fink_bindist

ls /sw/fink/debs/ | cut -f1 -d_ | sort | fgrep -v -x -f /tmp/fink_bindist | uniq
