#!/bin/sh
set -e

if [ -z "$BDBASE" ]; then
  echo "BDBASE not set"
  exit 1
fi
cd $BDBASE

# locations
source=$BDBASE
destination='fingolfin@shell.sourceforge.net:/home/groups/f/fi/fink/htdocs/bindist'

# rsync options
options="-e ssh -av --partial --progress"
# NOTE: data isn't compressed on the fly as practically all data is
#       already gzip-compressed

# make sure every directory has a index.php
$BDDATA/bdindex

# upload
echo rsync "$@" $options $source $destination
rsync "$@" $options $source $destination

exit 0
