#!/bin/sh
set -e

if [ -z "$BDBASE" ]; then
  echo "BDBASE not set"
  exit 1
fi
cd $BDBASE

# locations
source=$BDBASE
destination='shell1:/home/groups/f/fi/fink/htdocs'
if [ "$1" = "pippin" ]; then
  destination='pippin:/home/chrisp/fink/web'
fi

# rsync options
options="-e ssh -av --partial --progress"
options="$options --delete"
# NOTE: data isn't compressed on the fly as practically all data is
#       already gzip-compressed

# make sure every directory has a index.php
$BDDATA/bdindex

# upload
rsync $options $source $destination

exit 0
