#!/bin/sh
set -e

echo "Executing current.sql..."
$HOME/bin/finksql <current.sql

echo "Calculating flags..."
./flag

echo "Copying timestamp.inc..."
if [ -d /Volumes/src2/fink/pdb.finkproject.org/htdocs/pdb ]; then
  install -m 664 timestamp.inc /Volumes/src2/fink/pdb.finkproject.org/htdocs/pdb/
fi

exit 0

