#!/bin/sh
set -e

echo "Executing current.sql..."
./finksql <current.sql

echo "Calculating flags..."
./flag

echo "Copying timestamp.inc..."
if [ -d /var/www/www.finkproject.org/pdb ]; then
  install -m 664 timestamp.inc /var/www/www.finkproject.org/pdb/
fi

exit 0

