#!/bin/sh
cd /Volumes/src2/fink/pdb.finkproject.org/pdb

echo "Starting PDB update: `date`"
./refresh && ./inject

echo "Fixing permissions"
chgrp -R fink .
chmod -f -R g+w,a+r .
chgrp fink /Volumes/src2/fink/pdb.finkproject.org/htdocs/pdb/timestamp.inc

echo "Finished PDB update: `date`"
