#!/bin/sh
set -e

echo "Updating from CVS..."
if [ -d fink ]; then
  cd fink
  cvs -z3 -q update -A
  cd ..
else
  cvs -z3 -d:pserver:anonymous@cvs.sourceforge.net:/cvsroot/fink co -d fink dists
fi

# flush the previous dump
echo -n "" > current.sql

# Dump the 10.3 tree
rm -f fink/dists var/db/fink.db
ln -s 10.3 fink/dists
echo ""
echo "Dumping 10.3/stable..."
./dump 10.3 stable current-10.3-stable >>current.sql
echo ""
echo "Dumping 10.3/unstable..."
./dump 10.3 unstable current-10.3-unstable >>current.sql

# Dump the 10.4-transitional tree
rm -f fink/dists var/db/fink.db
ln -s 10.4-transitional fink/dists
echo ""
echo "Dumping 10.4-transitional/stable..."
./dump 10.4-transitional stable current-10.4-transitional-stable >>current.sql
echo ""
echo "Dumping 10.4-transitional/unstable..."
./dump 10.4-transitional unstable current-10.4-transitional-unstable >>current.sql

echo ""

exit 0
