#!/bin/sh
set -e

echo "Updating from CVS..."
if [ -d fink ]; then
  cd fink
  cvs -z3 -q update -Ad
  cd ..
else
  cvs -z3 -d:pserver:anonymous@cvs.sourceforge.net:/cvsroot/fink co -d fink dists
fi

# flush the previous dump
echo -n "" > current.sql

# Dump each supported source tree of the dists
for dist in 10.2-gcc3.3 10.3 10.4-transitional; do
    rm -f fink/dists var/db/fink.db
    ln -s $dist fink/dists
    echo ""
    echo "Dumping $dist/stable..."
    ./dump $dist stable current-$dist-stable >> current.sql
    echo ""
    echo "Dumping $dist/unstable..."
    ./dump $dist unstable current-$dist-unstable >> current.sql
done

echo ""

exit 0
