delete from sections;
insert into sections values ('base', 'Core packages');
insert into sections values ('crypto', 'Cryptographic software (subject to national regulations)');
insert into sections values ('database', 'SQL database software');
insert into sections values ('devel', 'Software for software development');
insert into sections values ('editors', 'Text editors');
insert into sections values ('games', 'Games and other fun stuff');
insert into sections values ('gnome', 'The GNOME desktop environment (version 1.2)');
insert into sections values ('graphics', 'Graphics applications and libraries');
insert into sections values ('languages', 'Programming languages (compilers, interpreters)');
insert into sections values ('libs', 'General purpose libraries');
insert into sections values ('net', 'Network-related applications and libraries');
insert into sections values ('sci', 'Scientific applications');
insert into sections values ('shells', 'Shells a.k.a. command line interpreters');
insert into sections values ('sound', 'Audio software');
insert into sections values ('text', 'Text-processing software');
insert into sections values ('utils', 'Utilities that don\'t fit elsewhere');
insert into sections values ('web', 'Web-related software');
insert into sections values ('x11', 'General X11 packages - toolkits and utilities');
insert into sections values ('x11-system', 'X Window System core packages');
insert into sections values ('x11-wm', 'Window managers for the X Window System');
