#!/bin/sh

#Copyright (c) 2005 Apple Computer, Inc.  All Rights Reserved.
#
#This program is free software; you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation; either version 2 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA


if [ -n "$1" ] ; then cd "$1" ; fi
if [ ! -d out -o ! -d logs -o ! -d pkginfo ]
	then echo "Please run this from inside a buildfink run directory." 2>&1
	echo "You may also specify the buildfink directory as an argument to this script." 2>&1
	exit 1
fi

rm -r out/* ; `dirname $0`/filter -F -o out -x `dirname $0`/../etc/filters.xml logs/*.log
