#!/usr/bin/perl

#Copyright (c) 2005 Apple Computer, Inc.  All Rights Reserved.
#
#This program is free software; you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation; either version 2 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

die "Usage: $0 a-dir b-dir\n" unless @ARGV == 2;
my($adir, $bdir) = (shift, shift);

print "<tt>\n";
while(<>) {
	s!^\s*(.*?): (.*) => (.*)!$1: <a href="$adir/logs/$1.log">$2</a> => <a href="$bdir/logs/$1.log">$3</a>!;
	s!$!<br>!;
	print $_;
}
print "</tt>\n";
